### ISSUE TITLE
Support query parameters

### ISSUE THREAD

**Issue by yakuter** [binalyze/httpreq#1]
We need to support query parameters. To do this we need a method like `SetParam(params map[string]interface{})`. Then this method will add the keys and values as query parameters to the requests.

**Comment by muratmirgun** [comment]
I can take this part on myself.

**Comment by yakuter** [comment]
Thank you @muratmirgun. I assigned you.

**Comment by muratmirgun** [comment]
Would it be a problem in this function if we set the query parameter type as `SetParam(params map[string]interface{})` ?

**Comment by yakuter** [comment]
It means we leave the responsibility to the user to convert numbers to string. Well I think this is ok for now. We can use map[string]string

**Comment by betelgeuse-7** [comment]
Can I also work on this feature? Sorry, I am asking this, because I am new to open source stuff.

**Comment by yakuter** [comment]
No problem @betelgeuse-7. Asking is a nice thing ;)

Unfortunately we already assigned @muratmirgun for this job. You should look for issues which not assigned for anybody.

**Comment by betelgeuse-7** [comment]
Thank you. I will be looking for other issues then. 
I forked this repository and pushed my implementation of SetParam to it. I will consider this as my first open source contribution :).

**Comment by yakuter** [comment]
I just checked it @betelgeuse-7 and it is nice. @muratmirgun you shoul also have a look at it:

https://github.com/betelgeuse-7/httpreq/commit/f499c45011ddad1da29378728fb096078237f7db

**Comment by muratmirgun** [comment]
This addition seems a bit too much. For example : `https://github.com/muratmirgun/httpreq/blob/1b189fe5747431b926c3d6d0c4d3b66339e623e7/request.go#L157`

**Comment by yakuter** [comment]
Ohhh yes, I didn't look at the code in detail. It is very dangerous to build URL yourself.

I saw your PR @muratmirgun. Waiting for you to add test and fix conflict in request.go.

**Comment by yakuter** [comment]
Closed with #10
