### ISSUE TITLE
Add context to request.

### ISSUE THREAD

**Issue by yakuter** [binalyze/httpreq#11]
We need context.Context to interrupt request. To do this, we should create new request like `New(ctx, address)`. Then we shoud create request with this context.

**Comment by gozeloglu** [comment]
Hi @yakuter. I'd like to take this issue. Can you assign to me?

**Comment by yakuter** [comment]
Great thank you @gozeloglu

**Comment by gozeloglu** [comment]
Do I need to add a new parameter to https://github.com/binalyze/httpreq/blob/ca5802840edc87b87ce0a5242a5ad5f57e2e9c57/request.go#L28 function? If I do that, this change will break the tests in `request_test.go`. Of course, I can change the all test functions. I just want to be sure about that.

**Comment by yakuter** [comment]
Yes we need to add ctx as first parameter. This is an important change, so we should change our tests too.
