### ISSUE TITLE
Support XML

### ISSUE THREAD

**Issue by yakuter** [binalyze/httpreq#3]
`httpreq` has only JSON support for now. However we should also support XML. To do this we need to;
1. add XML header `application/xml; charset=UTF-8` to request header
2. create a method like `SetBodyXML` to set our request body as XML.

**Comment by bariscanyilmaz** [comment]
I can add this support.

**Comment by yakuter** [comment]
Vreat, thank you @bariscanyilmaz. I assigned you now.
