### ISSUE TITLE
Configurable transport

### ISSUE THREAD

**Issue by yakuter** [binalyze/httpreq#6]
Golang http clients has transport layer. So our transport layer should be configurable from outside. To achieve this we need a `SetTransport` helper as in the example. Then this method overwrites our request's transport (r.client.Transport)

```go
transport := &http.Transport{
	// ...
}

req.SetTransport(transport)
```

**Comment by msrexe** [comment]
I can take this

**Comment by yakuter** [comment]
Great, thank you @msrexe
